#ClusterIP service for workers to connect to Jenkins.
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins-ns
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins